### ISSUE TITLE
confusing R error interpreting AF and AD fields as lists

### ISSUE THREAD

**Issue by jasteen** [tkoomar/VCFdbR#1]
Im trying to convert a VCF with 2 samples into a db.  The VCF is a merged vcf from bcftools, the original variant caller was vardict in pileup mode (we want the genotypes of each sample at each location on our panel).  The error I'm getting suggests that by AF and AD fields are lists, however I cant see how that is the case.

the error is

`Error in geno(tmp.vcf)[[col_name]][1, 1] : incorrect number of dimensions
Calls: source ... withVisible -> eval -> eval -> sapply -> sapply -> lapply -> FUN
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  geno column 'AD'is of upsupported type 'list. It will be skipped.
2: In FUN(X[[i]], ...) :
  geno column 'AF'is of upsupported type 'list. It will be skipped.
Execution halted
`

a sample line from the VCF is 

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Halo_ABCFS_0009-A12-BS008881_S272_L003.sorted.locatit	Halo_kConFab_0002_A09_99_002_0731_S657_L008.sorted.locatit

19	1206522	.	G	A	34	f0.1;v2;pSTD;q22.5;SN1.5;NM5.25;p8	SAMPLE=Halo-ABCFS-0013-B08-BS009256_S614_L007.sorted.locatit;TYPE=REF;VD=0;BIAS=2:0;REFBIAS=142:36;VARBIAS=0:0;PMEAN=36.7;PSTD=1;QUAL=36.8;QSTD=1;SBF=1;ODDRATI
O=0;MQ=60;SN=24.429;HIAF=1;ADJAF=0;SHIFT3=0;MSI=0;MSILEN=0;NM=0.4;HICNT=171;HICOV=171;LSEQ=0;RSEQ=0;DUPRATE=0;SPLITREAD=0;SPANPAIR=0;DP=224486;AF=0.0047;OLD_MULTIALLELIC=19:1206522:G/A/T/C;CSQ=A|5_prime_UTR_variant|MODIFIER|STK11|6794|Transcript|N
M_000455.4|protein_coding|1/10||NM_000455.4:c.-391G>A||725/3276|||||||1|||EntrezGene||rseq_mrna_match&rseq_ens_match_cds|G|G|||;AC=0;AN=4	GT:DP:VD:AD:AF:RD:ALD	0/0:156:0:156:.:121,35:0,0	0/0:118:0:118:.:102,16:0,0
```

am I doing something silly?  or is there an easy fix?

cheers

**Comment by tkoomar** [comment]
Thanks for the report including both the error and a sample line from the VCF. Can you please provide your VCF's header as well (at least the lines for the  FORMAT fields, but preferably the entire thing)?

From the sample line it does seem AF and AD should not be lists, but **I think maybe when multialleleic sties were split those fields might not have been updated in the header** (they may have `Number=A` instead of `Number=1`)

**Comment by tkoomar** [comment]
If you want something to try right away @jasteen , you can also try switching to the [geno-check-fix](https://github.com/tkoomar/VCFdbR/tree/geno-check-fix) branch, where I believe I have implemented safer type checking via a18b05bad2c7d633ba594065cb5eef35160a9ac2

**Comment by jasteen** [comment]
Thanks for the quick reply.  Your assumption about the header was correct in the first instance.  

```
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=SAMPLE,Number=1,Type=String,Description="Sample name (with whitespace translated to underscores)">
##INFO=<ID=TYPE,Number=1,Type=String,Description="Variant Type: SNV Insertion Deletion Complex">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##INFO=<ID=END,Number=1,Type=Integer,Description="Chr End Position">
##INFO=<ID=VD,Number=1,Type=Integer,Description="Variant Depth">
##INFO=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##INFO=<ID=BIAS,Number=1,Type=String,Description="Strand Bias Info">
##INFO=<ID=REFBIAS,Number=1,Type=String,Description="Reference depth by strand">
##INFO=<ID=VARBIAS,Number=1,Type=String,Description="Variant depth by strand">
##INFO=<ID=PMEAN,Number=1,Type=Float,Description="Mean position in reads">
##INFO=<ID=PSTD,Number=1,Type=Float,Description="Position STD in reads">
##INFO=<ID=QUAL,Number=1,Type=Float,Description="Mean quality score in reads">
##INFO=<ID=QSTD,Number=1,Type=Float,Description="Quality score STD in reads">
##INFO=<ID=SBF,Number=1,Type=Float,Description="Strand Bias Fisher p-value">
##INFO=<ID=ODDRATIO,Number=1,Type=Float,Description="Strand Bias Odds ratio">
##INFO=<ID=MQ,Number=1,Type=Float,Description="Mean Mapping Quality">
##INFO=<ID=SN,Number=1,Type=Float,Description="Signal to noise">
##INFO=<ID=HIAF,Number=1,Type=Float,Description="Allele frequency using only high quality bases">
##INFO=<ID=ADJAF,Number=1,Type=Float,Description="Adjusted AF for indels due to local realignment">
##INFO=<ID=SHIFT3,Number=1,Type=Integer,Description="No. of bases to be shifted to 3 prime for deletions due to alternative alignment">
##INFO=<ID=MSI,Number=1,Type=Float,Description="MicroSatellite. > 1 indicates MSI">
##INFO=<ID=MSILEN,Number=1,Type=Float,Description="MicroSatellite unit length in bp">
##INFO=<ID=NM,Number=1,Type=Float,Description="Mean mismatches in reads">
##INFO=<ID=LSEQ,Number=1,Type=String,Description="5' flanking seq">
##INFO=<ID=RSEQ,Number=1,Type=String,Description="3' flanking seq">
##INFO=<ID=GDAMP,Number=1,Type=Integer,Description="No. of amplicons supporting variant">
##INFO=<ID=TLAMP,Number=1,Type=Integer,Description="Total of amplicons covering variant">
##INFO=<ID=NCAMP,Number=1,Type=Integer,Description="No. of amplicons don't work">
##INFO=<ID=AMPFLAG,Number=1,Type=Integer,Description="Top variant in amplicons don't match">
##INFO=<ID=HICNT,Number=1,Type=Integer,Description="High quality variant reads">
##INFO=<ID=HICOV,Number=1,Type=Integer,Description="High quality total reads">
##INFO=<ID=SPLITREAD,Number=1,Type=Integer,Description="No. of split reads supporting SV">
##INFO=<ID=SPANPAIR,Number=1,Type=Integer,Description="No. of pairs supporting SV">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="SV type: INV DUP DEL INS FUS">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="The length of SV in bp">
##INFO=<ID=DUPRATE,Number=1,Type=Float,Description="Duplication rate in fraction">
##FILTER=<ID=q22.5,Description="Mean Base Quality Below 22.5">
##FILTER=<ID=Q10,Description="Mean Mapping Quality Below 10">
##FILTER=<ID=p8,Description="Mean Position in Reads Less than 8">
##FILTER=<ID=SN1.5,Description="Signal to Noise Less than 1.5">
##FILTER=<ID=Bias,Description="Strand Bias">
##FILTER=<ID=pSTD,Description="Position in Reads has STD of 0">
##FILTER=<ID=d3,Description="Total Depth < 3">
##FILTER=<ID=v2,Description="Var Depth < 2">
##FILTER=<ID=f0.1,Description="Allele frequency < 0.1">
##FILTER=<ID=MSI12,Description="Variant in MSI region with 12 non-monomer MSI or 13 monomer MSI">
##FILTER=<ID=NM5.25,Description="Mean mismatches in reads >= 5.25, thus likely false positive">
##FILTER=<ID=InGap,Description="The variant is in the deletion gap, thus likely false positive">
##FILTER=<ID=InIns,Description="The variant is adjacent to an insertion variant">
##FILTER=<ID=Cluster0bp,Description="Two variants are within 0 bp">
##FILTER=<ID=LongMSI,Description="The somatic variant is flanked by long A/T (>=14)">
##FILTER=<ID=AMPBIAS,Description="Indicate the variant has amplicon bias.">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=VD,Number=1,Type=Integer,Description="Variant Depth">
##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=AF,Number=A,Type=Float,Description="Allele Frequency">
##FORMAT=<ID=RD,Number=2,Type=Integer,Description="Reference forward, reverse reads">
##FORMAT=<ID=ALD,Number=2,Type=Integer,Description="Variant forward, reverse reads">
```

I modified AF and AD to Number=1, and that gets me a bit further down the pipeline. however now i'm getting the following error, and i'm not quite sure what its pointing to.  do I still have some multiallelics somewhere?  I've included the full trace, however it doesnt seem that I have any missing R modules or libraries.

```
 Rscript ~/scripts/git_controlled/VCFdbR/VCFdb.R --prefix output --vcf temp.vcf.gz --mode 'table'
Building a database where genotypes are saved to a table (variant_geno)
Loading required package: VariantAnnotation
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Loading required package: GenomeInfoDb
Loading required package: S4Vectors
Loading required package: stats4

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomicRanges
Loading required package: SummarizedExperiment
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: ‘matrixStats’

The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians


Attaching package: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from ‘package:base’:

    aperm, apply, rowsum

Loading required package: Rsamtools
Loading required package: Biostrings
Loading required package: XVector

Attaching package: ‘Biostrings’

The following object is masked from ‘package:base’:

    strsplit


Attaching package: ‘VariantAnnotation’

The following object is masked from ‘package:base’:

    tabulate

Loading required package: tidyverse
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
✔ ggplot2 3.3.2     ✔ purrr   0.3.4
✔ tibble  3.0.3     ✔ dplyr   1.0.2
✔ tidyr   1.1.0     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.5.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::collapse()   masks Biostrings::collapse(), IRanges::collapse()
✖ dplyr::combine()    masks Biobase::combine(), BiocGenerics::combine()
✖ purrr::compact()    masks XVector::compact()
✖ dplyr::count()      masks matrixStats::count()
✖ dplyr::desc()       masks IRanges::desc()
✖ tidyr::expand()     masks VariantAnnotation::expand(), S4Vectors::expand()
✖ dplyr::filter()     masks stats::filter()
✖ dplyr::first()      masks S4Vectors::first()
✖ stringr::fixed()    masks VariantAnnotation::fixed()
✖ dplyr::lag()        masks stats::lag()
✖ ggplot2::Position() masks BiocGenerics::Position(), base::Position()
✖ purrr::reduce()     masks GenomicRanges::reduce(), IRanges::reduce()
✖ dplyr::rename()     masks S4Vectors::rename()
✖ dplyr::select()     masks VariantAnnotation::select()
✖ purrr::simplify()   masks DelayedArray::simplify()
✖ dplyr::slice()      masks XVector::slice(), IRanges::slice()
######
LOADING RANGES
######
######
MERGING RANGES INTO CHUNKS
######
######
DONE IDENTIFYING CHUNKS
RANGES ARE WRITTEN TO:
output-chunk-ranges.rds
######
Building a database where genotypes are saved to a table (variant_geno)
Loading required package: dbplyr

Attaching package: ‘dbplyr’

The following objects are masked from ‘package:dplyr’:

    ident, sql

Loading required package: magrittr

Attaching package: ‘magrittr’

The following object is masked from ‘package:purrr’:

    set_names

The following object is masked from ‘package:tidyr’:

    extract

Loading required package: progress
Loading required package: RSQLite
######
PARSING VCF HEADER
######
######
CHECKING GENOTYPE FIELDS

Error in geno(tmp.vcf)[[col_name]][1, 1] : incorrect number of dimensions
Calls: source ... withVisible -> eval -> eval -> sapply -> sapply -> lapply -> FUN
Execution halted
```


i'll have a quick try of the geno-check-fix branch.

**Comment by jasteen** [comment]
The suggested branch gets a little further again


```
Loading required package: progress
Loading required package: RSQLite
######
PARSING VCF HEADER
######
######
CHECKING GENOTYPE FIELDS

######

######
STARTING TO BUILD DATABASE
######
New names:
* QUAL -> QUAL...7
* QUAL -> QUAL...20
Error: Can't recycle `..1` (size 1008) to match `..2` (size 2016).
Backtrace:
     █
  1. ├─base::source(paste0(this_dir, "/pipeline/02-build-db.R"))
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. ├─`%>%`(...)
  6. │ ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  7. │ └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  8. │   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  9. │     └─`_fseq`(`_lhs`)
 10. │       └─magrittr::freduce(value, `_function_list`)
 11. │         ├─base::withVisible(function_list[[k]](value))
 12. │         └─function_list[[k]](value)
 13. │           └─dplyr::bind_cols(...)
 14. │             └─vctrs::vec_cbind(!!!dots, .name_repair = .name_repair)

In addition: Warning message:
In FUN(X[[i]], ...) :
  geno column 'AF'is of upsupported type 'double. It will be skipped.
Execution halted
```

**Comment by tkoomar** [comment]
I think there are several things going on here:

1. The `AF` field was skipped because I forgot to add 'double' in the new type checking. _This has been fixed_ on the  geno-check-fix branch, so a fresh pull should fix that.  
2. You have an INFO field called `QUAL`, which is a duplicate name as the default VCF field `QUAL`. I do not _think_ this is causing the fatal error, but I am not 100% sure. Regardless, it does seem dangerous (ambiguous) to have 2 columns with the  same name, so I may implement checking of this earlier in the pipeline to alert the user if this is the case. 
3. I think maybe your `AD` should actually remain `Number=.` -- because even after splitting multialleleics, you should have 2 alleles, and thus 2 allele depths (so in reality, it should probably be `Number=2`). I am guessing the multialleleic splitting didn't properly parse the `AD` field which is why it sometimes only has 1 number. 

I added in several debugging messages to the geno-check-fix branch, so, if you can , please:
1. Pull and run again, sending along the log 
2. Try setting `AD` back to `Number=.` and running again

**Comment by jasteen** [comment]
ok, I feel like i'm close but just cant quite get it over the line:
I renamed the INFO/QUAL to INFO/QUAL2 (I could probably just remove it to be honest, we dont use much in the INFO fields)
removed INFO/DP, INFO/AD and INFO/VD (they seemed to be repeated in the INFO field and the FORMAT field)
Number=. didnt work, so I made it AD Number=2

here is the current header

```
##fileformat=VCFv4.1
##FILTER=<ID=PASS,Description="All filters passed">
##INFO=<ID=SAMPLE,Number=1,Type=String,Description="Sample name (with whitespace translated to underscores)">
##INFO=<ID=TYPE,Number=1,Type=String,Description="Variant Type: SNV Insertion Deletion Complex">
##INFO=<ID=END,Number=1,Type=Integer,Description="Chr End Position">
##INFO=<ID=BIAS,Number=1,Type=String,Description="Strand Bias Info">
##INFO=<ID=REFBIAS,Number=1,Type=String,Description="Reference depth by strand">
##INFO=<ID=VARBIAS,Number=1,Type=String,Description="Variant depth by strand">
##INFO=<ID=PMEAN,Number=1,Type=Float,Description="Mean position in reads">
##INFO=<ID=PSTD,Number=1,Type=Float,Description="Position STD in reads">
##INFO=<ID=QUAL2,Number=1,Type=Float,Description="Mean quality score in reads">
##INFO=<ID=QSTD,Number=1,Type=Float,Description="Quality score STD in reads">
##INFO=<ID=SBF,Number=1,Type=Float,Description="Strand Bias Fisher p-value">
##INFO=<ID=ODDRATIO,Number=1,Type=Float,Description="Strand Bias Odds ratio">
##INFO=<ID=MQ,Number=1,Type=Float,Description="Mean Mapping Quality">
##INFO=<ID=SN,Number=1,Type=Float,Description="Signal to noise">
##INFO=<ID=HIAF,Number=1,Type=Float,Description="Allele frequency using only high quality bases">
##INFO=<ID=ADJAF,Number=1,Type=Float,Description="Adjusted AF for indels due to local realignment">
##INFO=<ID=SHIFT3,Number=1,Type=Integer,Description="No. of bases to be shifted to 3 prime for deletions due to alternative alignment">
##INFO=<ID=MSI,Number=1,Type=Float,Description="MicroSatellite. > 1 indicates MSI">
##INFO=<ID=MSILEN,Number=1,Type=Float,Description="MicroSatellite unit length in bp">
##INFO=<ID=NM,Number=1,Type=Float,Description="Mean mismatches in reads">
##INFO=<ID=LSEQ,Number=1,Type=String,Description="5' flanking seq">
##INFO=<ID=RSEQ,Number=1,Type=String,Description="3' flanking seq">
##INFO=<ID=GDAMP,Number=1,Type=Integer,Description="No. of amplicons supporting variant">
##INFO=<ID=TLAMP,Number=1,Type=Integer,Description="Total of amplicons covering variant">
##INFO=<ID=NCAMP,Number=1,Type=Integer,Description="No. of amplicons don't work">
##INFO=<ID=AMPFLAG,Number=1,Type=Integer,Description="Top variant in amplicons don't match">
##INFO=<ID=HICNT,Number=1,Type=Integer,Description="High quality variant reads">
##INFO=<ID=HICOV,Number=1,Type=Integer,Description="High quality total reads">
##INFO=<ID=SPLITREAD,Number=1,Type=Integer,Description="No. of split reads supporting SV">
##INFO=<ID=SPANPAIR,Number=1,Type=Integer,Description="No. of pairs supporting SV">
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="SV type: INV DUP DEL INS FUS">
##INFO=<ID=SVLEN,Number=1,Type=Integer,Description="The length of SV in bp">
##INFO=<ID=DUPRATE,Number=1,Type=Float,Description="Duplication rate in fraction">
##FILTER=<ID=q22.5,Description="Mean Base Quality Below 22.5">
##FILTER=<ID=Q10,Description="Mean Mapping Quality Below 10">
##FILTER=<ID=p8,Description="Mean Position in Reads Less than 8">
##FILTER=<ID=SN1.5,Description="Signal to Noise Less than 1.5">
##FILTER=<ID=Bias,Description="Strand Bias">
##FILTER=<ID=pSTD,Description="Position in Reads has STD of 0">
##FILTER=<ID=d3,Description="Total Depth < 3">
##FILTER=<ID=v2,Description="Var Depth < 2">
##FILTER=<ID=f0.1,Description="Allele frequency < 0.1">
##FILTER=<ID=MSI12,Description="Variant in MSI region with 12 non-monomer MSI or 13 monomer MSI">
##FILTER=<ID=NM5.25,Description="Mean mismatches in reads >= 5.25, thus likely false positive">
##FILTER=<ID=InGap,Description="The variant is in the deletion gap, thus likely false positive">
##FILTER=<ID=InIns,Description="The variant is adjacent to an insertion variant">
##FILTER=<ID=Cluster0bp,Description="Two variants are within 0 bp">
##FILTER=<ID=LongMSI,Description="The somatic variant is flanked by long A/T (>=14)">
##FILTER=<ID=AMPBIAS,Description="Indicate the variant has amplicon bias.">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=VD,Number=1,Type=Integer,Description="Variant Depth">
##FORMAT=<ID=AD,Number=2,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=AF,Number=1,Type=Float,Description="Allele Frequency">
##FORMAT=<ID=RD,Number=2,Type=Integer,Description="Reference forward, reverse reads">
##FORMAT=<ID=ALD,Number=2,Type=Integer,Description="Variant forward, reverse reads">
```

and here is the current error

```
######
STARTING TO BUILD DATABASE
######
fixing 'AsIs' INFO columns
done parsing info
DP
VD
AD
Error: Can't recycle `..1` (size 1008) to match `..2` (size 2016).
Backtrace:
     █
  1. ├─base::source(paste0(this_dir, "/pipeline/02-build-db.R"))
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. ├─`%>%`(...)
  6. │ ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  7. │ └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  8. │   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  9. │     └─`_fseq`(`_lhs`)
 10. │       └─magrittr::freduce(value, `_function_list`)
 11. │         ├─base::withVisible(function_list[[k]](value))
 12. │         └─function_list[[k]](value)
 13. │           └─dplyr::bind_cols(...)
 14. │             └─vctrs::vec_cbind(!!!dots, .name_repair = .name_repair)

Execution halted
```

i'm going to do a test just removing any fields that spit an error and see if I can at least get it to complete on a something.
at this point i'm starting to think its me rather than anything your software is doing wrong.

**Comment by tkoomar** [comment]
I think what is happening here is a combination of both some odd formatting on your VCF, but also some oversights on my part. Thank you for helping me make VCFdbR better. 

**tl;dr I have a potential fix implemented on the geno-check-fix branch.** via e0d2a935622af74c73d75bb5e3d4c56f3cb28767 . Here are the caveats: 
1. Fields with `Number=.` (a variable number of values) are excluded. You can see below for why, but for now _if you want to keep those fields_ you should set them to `Number=1,Type=String` so they are imported as a character. 
2. Fields which have `Number=A` should be changed to `Number=1`. As long as  multialleleics have been properly split, these _should_ import OK
3. Fields with a _fixed_ number of values > 1 should now import OK, this just requires the `reshape2` package, (and may slow data import down slightly, I haven't benchmarked this yet). As an example, if your `RD` field is set to `Number=2`, it should lead to 2 columns in your final database: `rd_1` and `rd_2`. **Please let me know if this works as expected**. 

The issue is that I did not realize that when an annotation in a VCF has `Number`>1, the `readVcf()` function imports it as a 3D array. This was causing the strange `Error: Can't recycle ..1 (size 1008) to match ..2 (size 2016).` becuase the existing code assumed the data always imported as a (2D) matrix. This is now checked for, and if it is an array `reshape2::melt()` is used to convert the array into a 2D table with extra columns for each value. 

This is not a viable solution in the case of `Number=.` because in this case the annotation is imported as a matrix of lists (of variable size). I did figure out a way to separate these out on the [list_cols](https://github.com/tkoomar/VCFdbR/tree/list_cols) branch -- but it is very slow, and only works if all the lists are the same size. In essence, that means it only works in the case where the `Number` should be fixed anyway, so I do not plan to implement it. In the case that an annotation contains a truly uncertain number of values I doubt it would be very useful for filtering, so converting it to a string/character and parsing it after-the-fact seems an acceptable middle ground.

**Comment by jasteen** [comment]
looks ilke we are getting very close to it working.  not 100% sure where the "source" column is meant to come from.

```
fixing 'AsIs' INFO columns
done parsing info
DP
VD
AF
RD
ALD
done paring GENO
Done writing/insering variants
######
Done inserting variants
#####
There were 50 or more warnings (use warnings() to see the first 50)
######
BUILDING INDICIES
######
### done with variant ids on variant_info
### done with variant ids on variant_geno
### done with variant ids on variant impacts
### done with gene symbols
### done with gene IDs
## Indexing Variant Effects ##
## Indexing Allele Frequencies ##
######
DONE INDEXING
######
######
MAKING VARIANT RANGES OBJECT
######
######
MAKING GENE AND TRANSCRIPT MAPPING TABLE
######
Error: Can't subset columns that don't exist.
✖ Column `source` doesn't exist.
Backtrace:
     █
  1. ├─base::source(paste0(this_dir, "/pipeline/03-index-db.R"))
  2. │ ├─base::withVisible(eval(ei, envir))
  3. │ └─base::eval(ei, envir)
  4. │   └─base::eval(ei, envir)
  5. └─`%>%`(...)
  6.   ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  7.   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  8.     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  9.       └─`_fseq`(`_lhs`)
 10.         └─magrittr::freduce(value, `_function_list`)
 11.           └─function_list[[i]](value)
 12.             ├─dplyr::select(...)
 13.             └─dbplyr:::select.tbl_lazy(...)
 14.               └─tidyselect::vars_select(old_vars, !!!dots, .include = op_grps(.data$op
Execution halted
```

**Comment by tkoomar** [comment]
I just pushed a commit (e5c06e55dfc615b9634110954ec478ca1197a67f ) to geno-check-fix  that should handle this more safely and avoid this error.  The error you have here is from the very final step that just adds a supplementary table containing all of the genes which are found in the (optional) VEP annotations. In all other respects, the database should be fully functional. 

I am a bit confused though, as this table _should_ only get created if your VCF has VEP annotations (in a field called `CSQ`), which your VCF header does not indicate. For my own curiosity, could you run the below on your database, just so I can get a sense of what is going on? 

```{r}
db_name <- "PATH_TO_YOUR_DATABASE"
con <- DBI::dbConnect(RSQLite::SQLite(), db_name)
DBI::dbListTables(con)
dbplyr::tbl(con, 'variant_impact')
DBI::dbDisconnect(con)
```

**Comment by jasteen** [comment]
hmmm.   looking back, I cut off the bottom of the header, the CSQ section is under the contig section.

```
##contig=<ID=hs37d5,length=35477943,assembly=b37>
##bcftools_annotateVersion=1.8+htslib-1.8
##bcftools_annotateCommand=annotate -h /home/jste0021/vh83/reference/genomes/b37/vcf_contig_header_lines.txt -O z -o Halo-ABCFS-0013-B08-BS009256_S614_L007.sorted.locatit.reheader.vcf.gz Halo-ABCFS-0013-B08-BS009256_S614_L007.sorted.locatit.vardict.vcf; Date=Fri
 Nov  6 06:01:24 2020
##bcftools_viewVersion=1.8+htslib-1.8
##bcftools_viewCommand=view Halo-ABCFS-0013-B08-BS009256_S614_L007.sorted.locatit.reheader.vcf.gz; Date=Fri Nov  6 06:49:39 2020
##bcftools_viewCommand=view -O z -o Halo-ABCFS-0013-B08-BS009256_S614_L007.sorted.locatit.fixed.vcf.gz; Date=Fri Nov  6 06:49:39 2020
##bcftools_mergeVersion=1.8+htslib-1.8
##bcftools_mergeCommand=merge -m all -l temp_shorter_list_aa -O z -o temp_shorter_list_aa.merged.vcf.gz; Date=Sun Nov  8 10:19:48 2020
##bcftools_mergeCommand=merge -m all -O z -o merged.vardict.vcf.gz -l list3.txt; Date=Sun Nov  8 15:05:11 2020
##bcftools_filterVersion=1.8+htslib-1.8
##bcftools_filterCommand=filter -i COUNT(GT!="ref")>COUNT(GT="mis") -O z -o merged.vardict.filtered.vcf.gz merged.vardict.vcf.gz; Date=Sun Nov  8 15:55:23 2020
##INFO=<ID=OLD_MULTIALLELIC,Number=1,Type=String,Description="Original chr:pos:ref:alt encoding">
##INFO=<ID=OLD_VARIANT,Number=.,Type=String,Description="Original chr:pos:ref:alt encoding">
##VEP="v90" time="2020-11-08 16:19:26" cache="/usr/local/vep/90/ensembl-vep/cache/homo_sapiens_refseq/90_GRCh37" ensembl=90.4a44397 ensembl-variation=90.00c29b7 ensembl-funcgen=90.743f32b ensembl-io=90.9a148ea 1000genomes="phase3" COSMIC="81" ClinVar="201706" ES
P="20141103" HGMD-PUBLIC="20164" assembly="GRCh37.p13" dbSNP="150" gencode="GENCODE 19" genebuild="2011-04" gnomAD="170228" polyphen="2.2.2" refseq="01_2015" regbuild="1.0" sift="sift5.2.2"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_
variation|DISTANCE|STRAND|FLAGS|PICK|SYMBOL_SOURCE|HGNC_ID|REFSEQ_MATCH|GIVEN_REF|USED_REF|SIFT|PolyPhen|HGVS_OFFSET">
##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
```


```
> dbname <- "./output_shorter.db"                                                                                                                                                                                                                                     
> con <- DBI::dbConnect(RSQLite::SQLite(), db_name)
Error in stopifnot(length(dbname) == 1, !is.na(dbname)) : 
  object 'db_name' not found
> con <- DBI::dbConnect(RSQLite::SQLite(), dbname)                                                                                                                                                                                                                    
> DBI::dbListTables(con)
 [1] "FILTER"         "FORMAT"         "INFO"           "VEP"           
 [5] "contig"         "fileformat"     "samples"        "variant_geno"  
 [9] "variant_impact" "variant_info"  
> dbplyr::tbl(con, 'variant_impact')
Error: 'tbl' is not an exported object from 'namespace:dbplyr'
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> dbplyr::tbl(con, 'variant_impact')
Error: 'tbl' is not an exported object from 'namespace:dbplyr'
> dplyr::tbl(con, 'variant_impact')                                                                                                                                                                                                                                   
# Source:   table<variant_impact> [?? x 34]
# Database: sqlite 3.30.1
#   [/fs03/vh83/projects/brastrap/ALL_HALO/r_db/output_shorter.db]
   variant_id consequence impact symbol gene  feature_type feature biotype exon 
        <int> <chr>       <chr>  <chr>  <chr> <chr>        <chr>   <chr>   <chr>
 1          1 5_prime_UT… MODIF… STK11  6794  Transcript   NM_000… protei… 1/10 
 2          2 5_prime_UT… MODIF… STK11  6794  Transcript   XM_005… protei… 1/10 
 3          3 5_prime_UT… MODIF… STK11  6794  Transcript   XM_005… protei… 1/9  
 4          4 5_prime_UT… MODIF… STK11  6794  Transcript   NM_000… protei… 1/10 
 5          5 5_prime_UT… MODIF… STK11  6794  Transcript   XM_005… protei… 1/10 
 6          6 5_prime_UT… MODIF… STK11  6794  Transcript   XM_005… protei… 1/9  
 7          7 5_prime_UT… MODIF… STK11  6794  Transcript   NM_000… protei… 1/10 
 8          8 5_prime_UT… MODIF… STK11  6794  Transcript   XM_005… protei… 1/10 
 9          9 5_prime_UT… MODIF… STK11  6794  Transcript   XM_005… protei… 1/9  
10         10 5_prime_UT… MODIF… STK11  6794  Transcript   NM_000… protei… 1/10 
# … with more rows, and 25 more variables: intron <chr>, hgvsc <chr>,
#   hgvsp <chr>, cdna_position <chr>, cds_position <chr>,
#   protein_position <chr>, amino_acids <chr>, codons <chr>,
#   existing_variation <chr>, distance <chr>, strand <chr>, flags <chr>,
#   pick <chr>, symbol_source <chr>, hgnc_id <chr>, refseq_match <chr>,
#   given_ref <chr>, used_ref <chr>, sift <chr>, polyphen <chr>,
#   hgvs_offset <chr>, is_lof <int>, is_splicing <int>, is_exonic <int>,
#   is_intronic <int>
> DBI::dbDisconnect(con)
> exit
```

**Comment by tkoomar** [comment]
I see, thank you. It probably comes down to the specifics of the arguments given to VEP when it is run (in my testing it included both a `source` and a `symbol_source`). 

Regardless, I fixed an omission in the last commit to the geno-check-fix, and now I think it should be working correctly (my mistake for pushing before testing). Please pull it, give it a try, and let me know how it goes!

**Comment by jasteen** [comment]
the latest pull finishes perfectly.  thanks very much for your help.

**Comment by tkoomar** [comment]
Good to hear, I'l do a bit more testing before merging this to the maser branch, but will consider this issue closed.

**Comment by jasteen** [comment]
> 3. Fields with a _fixed_ number of values > 1 should now import OK, this just requires the `reshape2` package, (and may slow data import down slightly, I haven't benchmarked this yet). As an example, if your `RD` field is set to `Number=2`, it should lead to 2 columns in your final database: `rd_1` and `rd_2`. **Please let me know if this works as expected**.


can you tell me if this has been changed/broken in recent versions.  I did a git pull recently after not converting any VCF's for a while and our variant curator has pointed out that she really liked the rd_1 and rd_2 values (also the ALD ones).  they now error as multiallelic.  I tried to change number=1 and type=string (we can easily make these fields in sql later as long as we get the string imported), however I only get 1 value for each field, instead of the two values separated by a comma.  Is there an easy fix for this?
I currently have

##FORMAT=<ID=AD,Number=.,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
##FORMAT=<ID=AF,Number=.,Type=Float,Description="Allele Frequency">
##FORMAT=<ID=ALD,Number=2,Type=Integer,Description="Variant forward, reverse reads">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Total Depth">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=RD,Number=2,Type=Integer,Description="Reference forward, reverse reads">
##FORMAT=<ID=VD,Number=1,Type=Integer,Description="Variant Depth">

and an example format line from the VCF is:
GT:DP:VD:AD:AF:RD:ALD	0/0:36:0:36:.:28,8:0,0


cheers

**Comment by tkoomar** [comment]
Thanks for catching this. It turns out that I introduced a bug into how default arguments are handled during a merge. So, even when the `--include-multivalue-gt` flag was passed, it was being ignored. Please try a new pull from the master branch and let me know if it looks ok. In my testing, you should now properly get `rd_1` and `rd_2` columns in the `"variant_geno"` table.

**Comment by jasteen** [comment]
thanks for the quick reply as usual.


`Rscript ~/scripts/git_controlled/VCFdbR/VCFdb.R --prefix hopeful2 --vcf out2.vcf.gz --include-multivalue-gt --mode 'table'                                                                                                 
Including GENO Fields with multiple values (may be slow for many samples)
Building a database where genotypes are saved to a table (variant_geno)
Error in eval(ei, envir) : 
  A GRanges corresponding to chunks of variants to process must be passed with the `--chunks-ranges` argument
Calls: source -> withVisible -> eval -> eval
Execution halted
`

I tried setting --chunk_size as it seemed like it might be related, however I get `Error: Unknown argument: --chunk_size` 


this is the master branch that pulled with git pull

`remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 8 (delta 5), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/tkoomar/VCFdbR
   3b74101..e2b9383  master     -> origin/master
Updating 3b74101..e2b9383
Fast-forward
 README.md              | 13 +++++++++++++
 VCFdb.R                | 11 +++++++++++
 pipeline/02-build-db.R | 10 ++++++----
 3 files changed, 30 insertions(+), 4 deletions(-)
`

**Comment by tkoomar** [comment]
Thank you for including the output. There was a typo in the help text; the argument should actually be `--chunk-size`. 

However, I think your particular problem here  might result from bad cleanup of temporary files from a previous attempted run. If the working directory contains any of:`hopeful2.progress.RData` `hopeful2-variant-ranges.rds` or `hopeful2-chunk-ranges.rds`, try removing them and running again.

**Comment by jasteen** [comment]
you were right, i'd forgotten to clean up my work directory from a failed run.  thanks for all you help again.
